---
openapi: 3.0.0
info:
  title: Server
  description: Service for filesharing
servers:
  - url: '/'
components:
  schemas:
    Files:
      type: array
      properties:
        type: string
paths:
  '/files':
    get:
      tags:
        - Files
      summary: Get all files
      description: Get all files
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  '$ref': '#/components/schemas/Files'
        '400':
          description: Something wrong
  '/files/{filename}':
    get:
      tags:
        - Files
      summary: Get file
      description: Gets file
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  '$ref': '#/components/schemas/File'
        '400':
          description: Something wrong
